### PR TITLE
My social header

### PR DESCRIPTION
**Pull request by blackc0mb**
Hi, 
I would like to add my social header - Tonatiuh Morales -

I'm not sure if the index.html changes could impact your original repo, please let me know if I need to do something from my side.

### CODE REVIEW

**Review by Evavic44 — CHANGES_REQUESTED** [review]
Lol. You're only adding your social header to the README. The code remains the same.

**Comment by blackc0mb** [comment]
> Lol. You're only adding your social header to the README. The code remains the same.

Ups sorry. Let me undo the changes and make a new PR.

Do you have any way to not approve the PR?

**Comment by Evavic44** [comment]
> 
> 
> > Lol. You're only adding your social header to the README. The code remains the same.
> 
> Ups sorry. Let me undo the changes and make a new PR.
> 
> Do you have any way to not approve the PR?

Yeah, I could close it. If you want.

**Comment by blackc0mb** [comment]
> > > Lol. You're only adding your social header to the README. The code remains the same.
> > 
> > 
> > Ups sorry. Let me undo the changes and make a new PR.
> > Do you have any way to not approve the PR?
> 
> Yeah, I could close it. If you want.

Yes Eke please, thanks

**Pull request closed without merging**
